export type SizeTokens = {
  '4xs': string;
  '3xs': string;
  '2xs': string;
  xs: string;
  s: string;
  m: string;
  l: string;
  xl: string;
  '2xl': string;
  '3xl': string;
  '4xl': string;
  '5xl': string;
  '6xl': string;
  '7xl': string;
  '8xl': string;
  '9xl': string;
  '10xl': string;
  '11xl': string;
  '12xl': string;
  '13xl': string;
  '14xl': string;
  '15xl': string;
};
