/**
 * IMPORTANT
 * - Even though we have these imports here there is no reason to be worried about,
 *   all these imports are being added as devDependencies since are only be used inside
 *   the story files
 *
 * - This file has been added on the workspace of bit to be able to treat it as dev file in
 *   order to make all these inmports as devDependencies
 */

import { AddContent } from '@carlsberg/malty.icons.add-content';
import { AddEvent } from '@carlsberg/malty.icons.add-event';
import { AddProject } from '@carlsberg/malty.icons.add-project';
import { AddedDocument } from '@carlsberg/malty.icons.added-document';
import { Alert } from '@carlsberg/malty.icons.alert';
import { AlertConnection } from '@carlsberg/malty.icons.alert-connection';
import { AppDropbox } from '@carlsberg/malty.icons.app-dropbox';
import { AppFacebook } from '@carlsberg/malty.icons.app-facebook';
import { AppGithub } from '@carlsberg/malty.icons.app-github';
import { AppInstagram } from '@carlsberg/malty.icons.app-instagram';
import { AppLinkedin } from '@carlsberg/malty.icons.app-linkedin';
import { AppPowerbi } from '@carlsberg/malty.icons.app-powerbi';
import { AppSkype } from '@carlsberg/malty.icons.app-skype';
import { Arrange } from '@carlsberg/malty.icons.arrange';
import { ArrowSmallDown } from '@carlsberg/malty.icons.arrow-small-down';
import { ArrowSmallLeft } from '@carlsberg/malty.icons.arrow-small-left';
import { ArrowSmallRight } from '@carlsberg/malty.icons.arrow-small-right';
import { ArrowSmallUp } from '@carlsberg/malty.icons.arrow-small-up';
import { At } from '@carlsberg/malty.icons.at';
import { Attachment } from '@carlsberg/malty.icons.attachment';
import { Balance } from '@carlsberg/malty.icons.balance';
import { Bell } from '@carlsberg/malty.icons.bell';
import { BellNotification } from '@carlsberg/malty.icons.bell-notification';
import { Bold } from '@carlsberg/malty.icons.bold';
import { Book } from '@carlsberg/malty.icons.book';
import { Bookmark } from '@carlsberg/malty.icons.bookmark';
import { BookmarkFilled } from '@carlsberg/malty.icons.bookmark-filled';
import { Bottle } from '@carlsberg/malty.icons.bottle';
import { BottleCraft } from '@carlsberg/malty.icons.bottle-craft';
import { Calendar } from '@carlsberg/malty.icons.calendar';
import { CalendarAutumn } from '@carlsberg/malty.icons.calendar-autumn';
import { CalendarConfirm } from '@carlsberg/malty.icons.calendar-confirm';
import { CalendarEvents } from '@carlsberg/malty.icons.calendar-events';
import { CalendarSpring } from '@carlsberg/malty.icons.calendar-spring';
import { CalendarSummer } from '@carlsberg/malty.icons.calendar-summer';
import { CalendarWholeYear } from '@carlsberg/malty.icons.calendar-whole-year';
import { CalendarWinter } from '@carlsberg/malty.icons.calendar-winter';
import { Camera } from '@carlsberg/malty.icons.camera';
import { Can } from '@carlsberg/malty.icons.can';
import { Card } from '@carlsberg/malty.icons.card';
import { CardPlus } from '@carlsberg/malty.icons.card-plus';
import { CarlsbergFilled } from '@carlsberg/malty.icons.carlsberg-filled';
import { CarlsbergOutlined } from '@carlsberg/malty.icons.carlsberg-outlined';
import { CarretDown } from '@carlsberg/malty.icons.carret-down';
import { CarretLeft } from '@carlsberg/malty.icons.carret-left';
import { CarretMove } from '@carlsberg/malty.icons.carret-move';
import { CarretRight } from '@carlsberg/malty.icons.carret-right';
import { CarretUp } from '@carlsberg/malty.icons.carret-up';
import { Cart } from '@carlsberg/malty.icons.cart';
import { CartAdded } from '@carlsberg/malty.icons.cart-added';
import { CartLabel } from '@carlsberg/malty.icons.cart-label';
import { CartNotification } from '@carlsberg/malty.icons.cart-notification';
import { Change } from '@carlsberg/malty.icons.change';
import { Check } from '@carlsberg/malty.icons.check';
import { CheckboxCheck } from '@carlsberg/malty.icons.checkbox-check';
import { CheckboxCheckAlternate } from '@carlsberg/malty.icons.checkbox-check-alternate';
import { CheckboxCheckOutline } from '@carlsberg/malty.icons.checkbox-check-outline';
import { CheckboxCheckSquare } from '@carlsberg/malty.icons.checkbox-check-square';
import { CheckboxEmpty } from '@carlsberg/malty.icons.checkbox-empty';
import { ChevronDown } from '@carlsberg/malty.icons.chevron-down';
import { ChevronLeft } from '@carlsberg/malty.icons.chevron-left';
import { ChevronRight } from '@carlsberg/malty.icons.chevron-right';
import { ChevronUp } from '@carlsberg/malty.icons.chevron-up';
import { Clock } from '@carlsberg/malty.icons.clock';
import { ClockFilled } from '@carlsberg/malty.icons.clock-filled';
import { Clone } from '@carlsberg/malty.icons.clone';
import { Close } from '@carlsberg/malty.icons.close';
import { CoinDollar } from '@carlsberg/malty.icons.coin-dollar';
import { CoinEuro } from '@carlsberg/malty.icons.coin-euro';
import { Compass } from '@carlsberg/malty.icons.compass';
import { CompassFilled } from '@carlsberg/malty.icons.compass-filled';
import { Connected } from '@carlsberg/malty.icons.connected';
import { Contract } from '@carlsberg/malty.icons.contract';
import { Cookies } from '@carlsberg/malty.icons.cookies';
import { Coupon } from '@carlsberg/malty.icons.coupon';
import { Customer } from '@carlsberg/malty.icons.customer';
import { CustomerAdd } from '@carlsberg/malty.icons.customer-add';
import { CustomerQuestion } from '@carlsberg/malty.icons.customer-question';
import { Customers } from '@carlsberg/malty.icons.customers';
import { DataTransfer } from '@carlsberg/malty.icons.data-transfer';
import { DiagonalDownLeft } from '@carlsberg/malty.icons.diagonal-down-left';
import { DiagonalDownRight } from '@carlsberg/malty.icons.diagonal-down-right';
import { DiagonalUpLeft } from '@carlsberg/malty.icons.diagonal-up-left';
import { DiagonalUpRight } from '@carlsberg/malty.icons.diagonal-up-right';
import { Diploma } from '@carlsberg/malty.icons.diploma';
import { Diploma2 } from '@carlsberg/malty.icons.diploma2';
import { Download } from '@carlsberg/malty.icons.download';
import { Draughtmaster } from '@carlsberg/malty.icons.draughtmaster';
import { Edit } from '@carlsberg/malty.icons.edit';
import { EllipsisVertical } from '@carlsberg/malty.icons.ellipsis-vertical';
import { Email } from '@carlsberg/malty.icons.email';
import { Expand } from '@carlsberg/malty.icons.expand';
import { ExternalLink } from '@carlsberg/malty.icons.external-link';
import { EyeHide } from '@carlsberg/malty.icons.eye-hide';
import { EyeShow } from '@carlsberg/malty.icons.eye-show';
import { File } from '@carlsberg/malty.icons.file';
import { FilesCsv } from '@carlsberg/malty.icons.files-csv';
import { FilesJson } from '@carlsberg/malty.icons.files-json';
import { FilesPdf } from '@carlsberg/malty.icons.files-pdf';
import { FilesXls } from '@carlsberg/malty.icons.files-xls';
import { Filters } from '@carlsberg/malty.icons.filters';
import { Flash } from '@carlsberg/malty.icons.flash';
import { GlassGoblet } from '@carlsberg/malty.icons.glass-goblet';
import { GlassMug } from '@carlsberg/malty.icons.glass-mug';
import { GlassMugEmpty } from '@carlsberg/malty.icons.glass-mug-empty';
import { GlassWeissbier } from '@carlsberg/malty.icons.glass-weissbier';
import { Globe } from '@carlsberg/malty.icons.globe';
import { Headline } from '@carlsberg/malty.icons.headline';
import { Heart } from '@carlsberg/malty.icons.heart';
import { HeartFilled } from '@carlsberg/malty.icons.heart-filled';
import { Help } from '@carlsberg/malty.icons.help';
import { HideMenu } from '@carlsberg/malty.icons.hide-menu';
import { History } from '@carlsberg/malty.icons.history';
import { Home } from '@carlsberg/malty.icons.home';
import { Hop } from '@carlsberg/malty.icons.hop';
import { Image } from '@carlsberg/malty.icons.image';
import { Information } from '@carlsberg/malty.icons.information';
import { Italic } from '@carlsberg/malty.icons.italic';
import { ItemAdd } from '@carlsberg/malty.icons.item-add';
import { ItemBlock } from '@carlsberg/malty.icons.item-block';
import { ItemCheck } from '@carlsberg/malty.icons.item-check';
import { ItemCheckDefault } from '@carlsberg/malty.icons.item-check-default';
import { ItemCheckFilled } from '@carlsberg/malty.icons.item-check-filled';
import { ItemClose } from '@carlsberg/malty.icons.item-close';
import { ItemCloseFilled } from '@carlsberg/malty.icons.item-close-filled';
import { Library } from '@carlsberg/malty.icons.library';
import { Loading } from '@carlsberg/malty.icons.loading';
import { LocationIp } from '@carlsberg/malty.icons.location-ip';
import { Lock } from '@carlsberg/malty.icons.lock';
import { LockOpen } from '@carlsberg/malty.icons.lock-open';
import { Map } from '@carlsberg/malty.icons.map';
import { Market } from '@carlsberg/malty.icons.market';
import { MediaPause } from '@carlsberg/malty.icons.media-pause';
import { MediaPlay } from '@carlsberg/malty.icons.media-play';
import { MediaSound } from '@carlsberg/malty.icons.media-sound';
import { MediaSoundOff } from '@carlsberg/malty.icons.media-sound-off';
import { MediaStop } from '@carlsberg/malty.icons.media-stop';
import { Menu } from '@carlsberg/malty.icons.menu';
import { MenuLeft } from '@carlsberg/malty.icons.menu-left';
import { MenuRight } from '@carlsberg/malty.icons.menu-right';
import { Minus } from '@carlsberg/malty.icons.minus';
import { Mobile } from '@carlsberg/malty.icons.mobile';
import { More } from '@carlsberg/malty.icons.more';
import { Mouse } from '@carlsberg/malty.icons.mouse';
import { Notepad } from '@carlsberg/malty.icons.notepad';
import { Outlet } from '@carlsberg/malty.icons.outlet';
import { OutletPlus } from '@carlsberg/malty.icons.outlet-plus';
import { Pack } from '@carlsberg/malty.icons.pack';
import { PackageKeg } from '@carlsberg/malty.icons.package-keg';
import { PackageWholesaler } from '@carlsberg/malty.icons.package-wholesaler';
import { Paint } from '@carlsberg/malty.icons.paint';
import { Pallet } from '@carlsberg/malty.icons.pallet';
import { Pencil } from '@carlsberg/malty.icons.pencil';
import { PhoneClassic } from '@carlsberg/malty.icons.phone-classic';
import { Pilsner } from '@carlsberg/malty.icons.pilsner';
import { Pin } from '@carlsberg/malty.icons.pin';
import { PinActive } from '@carlsberg/malty.icons.pin-active';
import { PinChurn } from '@carlsberg/malty.icons.pin-churn';
import { PinClosed } from '@carlsberg/malty.icons.pin-closed';
import { PinInactive } from '@carlsberg/malty.icons.pin-inactive';
import { PinIndirect } from '@carlsberg/malty.icons.pin-indirect';
import { PinLabeling } from '@carlsberg/malty.icons.pin-labeling';
import { PinParked } from '@carlsberg/malty.icons.pin-parked';
import { PinProspect } from '@carlsberg/malty.icons.pin-prospect';
import { PinSeveral } from '@carlsberg/malty.icons.pin-several';
import { Pint } from '@carlsberg/malty.icons.pint';
import { Plus } from '@carlsberg/malty.icons.plus';
import { Power } from '@carlsberg/malty.icons.power';
import { RadiobuttonOff } from '@carlsberg/malty.icons.radiobutton-off';
import { RadiobuttonOn } from '@carlsberg/malty.icons.radiobutton-on';
import { Refresh } from '@carlsberg/malty.icons.refresh';
import { Restaurant } from '@carlsberg/malty.icons.restaurant';
import { Retry } from '@carlsberg/malty.icons.retry';
import { Salesrep } from '@carlsberg/malty.icons.salesrep';
import { Save } from '@carlsberg/malty.icons.save';
import { Search } from '@carlsberg/malty.icons.search';
import { SearchUser } from '@carlsberg/malty.icons.search-user';
import { Sent } from '@carlsberg/malty.icons.sent';
import { Settings } from '@carlsberg/malty.icons.settings';
import { Share } from '@carlsberg/malty.icons.share';
import { ShieldExclamation } from '@carlsberg/malty.icons.shield-exclamation';
import { ShieldSecurity } from '@carlsberg/malty.icons.shield-security';
import { Shop } from '@carlsberg/malty.icons.shop';
import { SignOut } from '@carlsberg/malty.icons.sign-out';
import { Sort } from '@carlsberg/malty.icons.sort';
import { SpeachBalloon } from '@carlsberg/malty.icons.speach-balloon';
import { SpeachBalloonComplaint } from '@carlsberg/malty.icons.speach-balloon-complaint';
import { SpeachBalloonLivechat } from '@carlsberg/malty.icons.speach-balloon-livechat';
import { Star } from '@carlsberg/malty.icons.star';
import { StarFilled } from '@carlsberg/malty.icons.star-filled';
import { Survey } from '@carlsberg/malty.icons.survey';
import { SurveyCheck } from '@carlsberg/malty.icons.survey-check';
import { SurveyCheckbox } from '@carlsberg/malty.icons.survey-checkbox';
import { SurveyDefault } from '@carlsberg/malty.icons.survey-default';
import { SurveyTrophy } from '@carlsberg/malty.icons.survey-trophy';
import { Sync } from '@carlsberg/malty.icons.sync';
import { Tap } from '@carlsberg/malty.icons.tap';
import { TapGlass } from '@carlsberg/malty.icons.tap-glass';
import { TechnicalSupport } from '@carlsberg/malty.icons.technical-support';
import { Text } from '@carlsberg/malty.icons.text';
import { ThirdParty } from '@carlsberg/malty.icons.third-party';
import { ThumbDown } from '@carlsberg/malty.icons.thumb-down';
import { ThumbUp } from '@carlsberg/malty.icons.thumb-up';
import { ToggleOff } from '@carlsberg/malty.icons.toggle-off';
import { ToggleOn } from '@carlsberg/malty.icons.toggle-on';
import { Trash } from '@carlsberg/malty.icons.trash';
import { Trophy } from '@carlsberg/malty.icons.trophy';
import { Truck } from '@carlsberg/malty.icons.truck';
import { Tulipe } from '@carlsberg/malty.icons.tulipe';
import { Twitter } from '@carlsberg/malty.icons.twitter';
import { Underline } from '@carlsberg/malty.icons.underline';
import { Upload } from '@carlsberg/malty.icons.upload';
import { ViewGrid } from '@carlsberg/malty.icons.view-grid';
import { ViewList } from '@carlsberg/malty.icons.view-list';
import { Volume } from '@carlsberg/malty.icons.volume';
import { Wheat } from '@carlsberg/malty.icons.wheat';
import { World } from '@carlsberg/malty.icons.world';
import React, { ReactElement } from 'react';

export const allIcons = [
  { component: AddContent, name: 'AddContent' },
  { component: AddEvent, name: 'AddEvent' },
  { component: AddProject, name: 'AddProject' },
  { component: AddedDocument, name: 'AddedDocument' },
  { component: Alert, name: 'Alert' },
  { component: AlertConnection, name: 'AlertConnection' },
  { component: AppDropbox, name: 'AppDropbox' },
  { component: AppFacebook, name: 'AppFacebook' },
  { component: AppGithub, name: 'AppGithub' },
  { component: AppInstagram, name: 'AppInstagram' },
  { component: AppLinkedin, name: 'AppLinkedin' },
  { component: AppPowerbi, name: 'AppPowerbi' },
  { component: AppSkype, name: 'AppSkype' },
  { component: Arrange, name: 'Arrange' },
  { component: ArrowSmallDown, name: 'ArrowSmallDown' },
  { component: ArrowSmallLeft, name: 'ArrowSmallLeft' },
  { component: ArrowSmallRight, name: 'ArrowSmallRight' },
  { component: ArrowSmallUp, name: 'ArrowSmallUp' },
  { component: At, name: 'At' },
  { component: Attachment, name: 'Attachment' },
  { component: Balance, name: 'Balance' },
  { component: Bell, name: 'Bell' },
  { component: BellNotification, name: 'BellNotification' },
  { component: Bold, name: 'Bold' },
  { component: Book, name: 'Book' },
  { component: Bookmark, name: 'Bookmark' },
  { component: BookmarkFilled, name: 'BookmarkFilled' },
  { component: Bottle, name: 'Bottle' },
  { component: BottleCraft, name: 'BottleCraft' },
  { component: Calendar, name: 'Calendar' },
  { component: CalendarAutumn, name: 'CalendarAutumn' },
  { component: CalendarConfirm, name: 'CalendarConfirm' },
  { component: CalendarEvents, name: 'CalendarEvents' },
  { component: CalendarSpring, name: 'CalendarSpring' },
  { component: CalendarSummer, name: 'CalendarSummer' },
  { component: CalendarWholeYear, name: 'CalendarWholeYear' },
  { component: CalendarWinter, name: 'CalendarWinter' },
  { component: Camera, name: 'Camera' },
  { component: Can, name: 'Can' },
  { component: Card, name: 'Card' },
  { component: CardPlus, name: 'CardPlus' },
  { component: CarlsbergFilled, name: 'CarlsbergFilled' },
  { component: CarlsbergOutlined, name: 'CarlsbergOutlined' },
  { component: CarretDown, name: 'CarretDown' },
  { component: CarretLeft, name: 'CarretLeft' },
  { component: CarretMove, name: 'CarretMove' },
  { component: CarretRight, name: 'CarretRight' },
  { component: CarretUp, name: 'CarretUp' },
  { component: Cart, name: 'Cart' },
  { component: CartAdded, name: 'CartAdded' },
  { component: CartLabel, name: 'CartLabel' },
  { component: CartNotification, name: 'CartNotification' },
  { component: Change, name: 'Change' },
  { component: Check, name: 'Check' },
  { component: CheckboxCheck, name: 'CheckboxCheck' },
  { component: CheckboxCheckAlternate, name: 'CheckboxCheckAlternate' },
  { component: CheckboxCheckOutline, name: 'CheckboxCheckOutline' },
  { component: CheckboxCheckSquare, name: 'CheckboxCheckSquare' },
  { component: CheckboxEmpty, name: 'CheckboxEmpty' },
  { component: ChevronDown, name: 'ChevronDown' },
  { component: ChevronLeft, name: 'ChevronLeft' },
  { component: ChevronRight, name: 'ChevronRight' },
  { component: ChevronUp, name: 'ChevronUp' },
  { component: Clock, name: 'Clock' },
  { component: ClockFilled, name: 'ClockFilled' },
  { component: Clone, name: 'Clone' },
  { component: Close, name: 'Close' },
  { component: CoinDollar, name: 'CoinDollar' },
  { component: CoinEuro, name: 'CoinEuro' },
  { component: Compass, name: 'Compass' },
  { component: CompassFilled, name: 'CompassFilled' },
  { component: Connected, name: 'Connected' },
  { component: Contract, name: 'Contract' },
  { component: Cookies, name: 'Cookies' },
  { component: Coupon, name: 'Coupon' },
  { component: Customer, name: 'Customer' },
  { component: CustomerAdd, name: 'CustomerAdd' },
  { component: CustomerQuestion, name: 'CustomerQuestion' },
  { component: Customers, name: 'Customers' },
  { component: DataTransfer, name: 'DataTransfer' },
  { component: DiagonalDownLeft, name: 'DiagonalDownLeft' },
  { component: DiagonalDownRight, name: 'DiagonalDownRight' },
  { component: DiagonalUpLeft, name: 'DiagonalUpLeft' },
  { component: DiagonalUpRight, name: 'DiagonalUpRight' },
  { component: Diploma, name: 'Diploma' },
  { component: Diploma2, name: 'Diploma2' },
  { component: Download, name: 'Download' },
  { component: Draughtmaster, name: 'Draughtmaster' },
  { component: Edit, name: 'Edit' },
  { component: EllipsisVertical, name: 'EllipsisVertical' },
  { component: Email, name: 'Email' },
  { component: Expand, name: 'Expand' },
  { component: ExternalLink, name: 'ExternalLink' },
  { component: EyeShow, name: 'EyeShow' },
  { component: EyeHide, name: 'EyeHide' },
  { component: File, name: 'File' },
  { component: FilesCsv, name: 'FilesCsv' },
  { component: FilesJson, name: 'FilesJson' },
  { component: FilesPdf, name: 'FilesPdf' },
  { component: FilesXls, name: 'FilesXls' },
  { component: Filters, name: 'Filters' },
  { component: Flash, name: 'Flash' },
  { component: GlassGoblet, name: 'GlassGoblet' },
  { component: GlassMug, name: 'GlassMug' },
  { component: GlassMugEmpty, name: 'GlassMugEmpty' },
  { component: GlassWeissbier, name: 'GlassWeissbier' },
  { component: Globe, name: 'Globe' },
  { component: Headline, name: 'Headline' },
  { component: Heart, name: 'Heart' },
  { component: HeartFilled, name: 'HeartFilled' },
  { component: Help, name: 'Help' },
  { component: HideMenu, name: 'HideMenu' },
  { component: History, name: 'History' },
  { component: Home, name: 'Home' },
  { component: Hop, name: 'Hop' },
  { component: Image, name: 'Image' },
  { component: Information, name: 'Information' },
  { component: Italic, name: 'Italic' },
  { component: ItemAdd, name: 'ItemAdd' },
  { component: ItemBlock, name: 'ItemBlock' },
  { component: ItemCheck, name: 'ItemCheck' },
  { component: ItemCheckDefault, name: 'ItemCheckDefault' },
  { component: ItemCheckFilled, name: 'ItemCheckFilled' },
  { component: ItemClose, name: 'ItemClose' },
  { component: ItemCloseFilled, name: 'ItemCloseFilled' },
  { component: Library, name: 'Library' },
  { component: Loading, name: 'Loading' },
  { component: LocationIp, name: 'LocationIp' },
  { component: Lock, name: 'Lock' },
  { component: LockOpen, name: 'LockOpen' },
  { component: Map, name: 'Map' },
  { component: Market, name: 'Market' },
  { component: MediaPause, name: 'MediaPause' },
  { component: MediaPlay, name: 'MediaPlay' },
  { component: MediaSound, name: 'MediaSound' },
  { component: MediaSoundOff, name: 'MediaSoundOff' },
  { component: MediaStop, name: 'MediaStop' },
  { component: Menu, name: 'Menu' },
  { component: MenuLeft, name: 'MenuLeft' },
  { component: MenuRight, name: 'MenuRight' },
  { component: Minus, name: 'Minus' },
  { component: Mobile, name: 'Mobile' },
  { component: More, name: 'More' },
  { component: Mouse, name: 'Mouse' },
  { component: Notepad, name: 'Notepad' },
  { component: Outlet, name: 'Outlet' },
  { component: OutletPlus, name: 'OutletPlus' },
  { component: Pack, name: 'Pack' },
  { component: PackageKeg, name: 'PackageKeg' },
  { component: PackageWholesaler, name: 'PackageWholesaler' },
  { component: Paint, name: 'Paint' },
  { component: Pallet, name: 'Pallet' },
  { component: Pencil, name: 'Pencil' },
  { component: PhoneClassic, name: 'PhoneClassic' },
  { component: Pilsner, name: 'Pilsner' },
  { component: Pin, name: 'Pin' },
  { component: PinActive, name: 'PinActive' },
  { component: PinChurn, name: 'PinChurn' },
  { component: PinClosed, name: 'PinClosed' },
  { component: PinInactive, name: 'PinInactive' },
  { component: PinIndirect, name: 'PinIndirect' },
  { component: PinLabeling, name: 'PinLabeling' },
  { component: PinParked, name: 'PinParked' },
  { component: PinProspect, name: 'PinProspect' },
  { component: PinSeveral, name: 'PinSeveral' },
  { component: Pint, name: 'Pint' },
  { component: Plus, name: 'Plus' },
  { component: Power, name: 'Power' },
  { component: RadiobuttonOff, name: 'RadiobuttonOff' },
  { component: RadiobuttonOn, name: 'RadiobuttonOn' },
  { component: Refresh, name: 'Refresh' },
  { component: Restaurant, name: 'Restaurant' },
  { component: Retry, name: 'Retry' },
  { component: Salesrep, name: 'Salesrep' },
  { component: Save, name: 'Save' },
  { component: Search, name: 'Search' },
  { component: SearchUser, name: 'SearchUser' },
  { component: Sent, name: 'Sent' },
  { component: Settings, name: 'Settings' },
  { component: Share, name: 'Share' },
  { component: ShieldExclamation, name: 'ShieldExclamation' },
  { component: ShieldSecurity, name: 'ShieldSecurity' },
  { component: Shop, name: 'Shop' },
  { component: SignOut, name: 'SignOut' },
  { component: Sort, name: 'Sort' },
  { component: SpeachBalloon, name: 'SpeachBalloon' },
  { component: SpeachBalloonComplaint, name: 'SpeachBalloonComplaint' },
  { component: SpeachBalloonLivechat, name: 'SpeachBalloonLivechat' },
  { component: Star, name: 'Star' },
  { component: StarFilled, name: 'StarFilled' },
  { component: Survey, name: 'Survey' },
  { component: SurveyCheck, name: 'SurveyCheck' },
  { component: SurveyCheckbox, name: 'SurveyCheckbox' },
  { component: SurveyDefault, name: 'SurveyDefault' },
  { component: SurveyTrophy, name: 'SurveyTrophy' },
  { component: Sync, name: 'Sync' },
  { component: Tap, name: 'Tap' },
  { component: TapGlass, name: 'TapGlass' },
  { component: TechnicalSupport, name: 'TechnicalSupport' },
  { component: Text, name: 'Text' },
  { component: ThirdParty, name: 'ThirdParty' },
  { component: ThumbDown, name: 'ThumbDown' },
  { component: ThumbUp, name: 'ThumbUp' },
  { component: ToggleOff, name: 'ToggleOff' },
  { component: ToggleOn, name: 'ToggleOn' },
  { component: Trash, name: 'Trash' },
  { component: Trophy, name: 'Trophy' },
  { component: Truck, name: 'Truck' },
  { component: Tulipe, name: 'Tulipe' },
  { component: Twitter, name: 'Twitter' },
  { component: Underline, name: 'Underline' },
  { component: Upload, name: 'Upload' },
  { component: ViewGrid, name: 'ViewGrid' },
  { component: ViewList, name: 'ViewList' },
  { component: Volume, name: 'Volume' },
  { component: Wheat, name: 'Wheat' },
  { component: World, name: 'World' }
];

export const allIconsStoryOptions = allIcons.reduce(
  (options: Record<string, ReactElement>, { name, component: Icon }) => ({ ...options, [name]: <Icon /> }),
  {}
);
